
["Structures Spawn"]
	#disables the structure spawn from apocalypse now
	structure_spawn = true

["Increase in Population Density"]
	#Change from 0.1 to 0.5 to increase the number of walkers that appear
	population_density = 0.0

["Walkers and Runners spawn"]
	#disables the spawn of walkers and runners in this mod
	walkers_runners_spawn = true

["Humans Spawn"]
	#disables the spawn of humans in this mod
	humans_spawn = true

["Ambient Spawn"]
	#disables the spawn of ambient creatures spawn in this mod
	ambient_spawn = true

